# .readthedocs.yaml
version: 2

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Python settings
python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt  # jeśli masz dodatkowe paczki, inaczej można pominąć
